### ISSUE TITLE
No specs found

### ISSUE THREAD

**Issue by joshmedeski** [LazyVim/starter#1]
I've created the starter and when it runs it shows me this error:

```
Error detected while processing /Users/joshmedeski/.config/nvim/init.lua:
No specs found for module lazyvim.plugins
Press ENTER or type command to continue
```

I've confirmed that `LazyVim/LazyVim` is properly installed, but [this line](https://github.com/LazyVim/starter/blob/main/lua/config/lazy.lua#L12) seems to be failing.

Any ideas?

**Comment by folke** [comment]
Can you delete the lazy cache? `~/.cache/nvim/lazy/cache`.

That should fix it. I'm currently working on a proper fix for this.

Let me know if that works!

**Comment by joshmedeski** [comment]
Yes, that was it! I've forked LazyVim and want to contribute :)
