### ISSUE TITLE
Make checker disabled by default to increase stability of LazyVim

### ISSUE THREAD

**Issue by monoira** [LazyVim/starter#107]
Currently checker is on, which is just distracting people, often at the bad time too.
Updating LazyVim is pretty eazy, but sometimes updates break something at the WRONG TIME.
Let people decide when to update themselves. After all, if they are smart enough to use Neovim, they are smart enough to know how to press space + l  and S when they have free time.

```lua
-- at lua/config/lazy.lua
  checker = {
    enabled = true, -- check for plugin updates periodically
  },
```

**Comment by folke** [comment]
check again....
checker notifications are disabled.
checker is only enabled to show the lualine component.

Besides, users are smart enough to change the settings if they don't like them.
