### ISSUE TITLE
Add Dart LSP following the example.lua configuration style

### ISSUE THREAD

**Issue by ferrarafer** [LazyVim/starter#12]
Hi! Excellent work with `LazyVim` and this `starter`, congratulations! I want to add Dart Lsp to the example.lua configuration but I don't realize how to do it. I tried multiple ways without any luck. Can you give me a direction on how to resolve it? I made it work with the following code in a separate files inside plugins folder but I want to follow the same structure as in example.lua if possible.

```
require'lspconfig'.dartls.setup{ 
  cmd = { "dart", 'language-server', '--protocol=lsp' }, 
}

```
Thanks in advance!

**Comment by ferrarafer** [comment]
I was able to do it with the following code, I don't know if it is the cleaner way because I didn't want to use a function just tables.

```
return {
  "neovim/nvim-lspconfig",
  enabled = true,
  opts = function()
    require("lspconfig").dartls.setup({
      cmd = { "dart", "language-server", "--protocol=lsp" },
    })
  end,
}

```

**Comment by folke** [comment]
Please check the docs. It's all in there:  https://www.lazyvim.org/plugins/lsp#nvim-lspconfig

You should set `opts.servers.dartls`
