### ISSUE TITLE
Telescope current_buffer_fuzzy_find with treesitter crashes

### ISSUE THREAD

**Issue by craftyprash** [LazyVim/starter#2]
I have had good success with the earlier setup of `lazy` plugin manager by referencing your dotfiles :) 
But as I noticed you have put this starter template out, was giving it a try.

While everything else seems fine. Here's the issue I have run into so far:

I just cloned the starter template and launched nvim
On searching the `current buffer` using the provided keymap `<leader>sb` the below error occurs.

This surely isn't a starter/LazyVim specific issue, but it probably relates to the version you might be pulling, hence sharing here.

```
Error executing Lua callback: ...im/lazy/telescope.nvim/lua/telescope/builtin/__files.lua:413: attempt to call method '_get_hl_from_capture' (a nil value)
stack traceback:
	...im/lazy/telescope.nvim/lua/telescope/builtin/__files.lua:413: in function 'v'
	...im/lazy/telescope.nvim/lua/telescope/builtin/__files.lua:529: in function 'v'
	.../nvim/lazy/telescope.nvim/lua/telescope/builtin/init.lua:514: in function <.../nvim/lazy/telescope.nvim/lua/telescope/builtin/init.lua:483>
	...share/nvim/lazy/telescope.nvim/lua/telescope/command.lua:188: in function 'run_command'
	...share/nvim/lazy/telescope.nvim/lua/telescope/command.lua:253: in function 'load_command'
	...ocal/share/nvim/lazy/telescope.nvim/plugin/telescope.lua:109: in function <...ocal/share/nvim/lazy/telescope.nvim/plugin/telescope.lua:108>
```

This looks more like an issue with the Telescope version in use along with treesitter enabled. 
Note: Other Telescope and treesitter features do work.

Let me know if you need more details. Also, if you could help point out what needs to be changed for this to work - in case it's not a generic issue you / others are running into?

I do have `ripgrep` installed through `brew` on my mac.

**Comment by folke** [comment]
It seems that Telescope only has one release and that's from July 2022.
That's not good. I'll change it to pull in `HEAD` instead for now.

**Comment by folke** [comment]
Updated...

**Comment by craftyprash** [comment]
Works now, thanks!
