### ISSUE TITLE
Seeking suggestions on customizing, "making it mine"

### ISSUE THREAD

**Issue by knodalyte** [LazyVim/starter#20]
A great way to create a fully functional nvim! What would be my options, and your suggestions, on best ways to customize for my preferences? 

I have [re]configured nvim several times, more recently to go mostly all Lua, and most recently to move to Lazy, so I know how to do that, and I know I could copy the configs from the LazyVim directory as a starting point, but not sure if I want to get future updates to LazyVim or not, and how to deal with possible conflicts with my customizations.

**Comment by folke** [comment]
Please read the LAzyVim docs. You are not supposed to clone and merge updates from LAzyVim. It's just a plugin.
