### ISSUE TITLE
Please provide a dockerfile 

### ISSUE THREAD

**Issue by SamPosh** [LazyVim/starter#21]
Please provide a dockerfile so that we can use it directly. Mostly we need a ubuntu container
some thing like this which is available for lunarVim.
https://raw.githubusercontent.com/LunarVim/LunarVim/master/utils/docker/Dockerfile.remote

Thanks in advance

**Comment by jellydn** [comment]
This is the way I'm testing [my LazyVim](https://github.com/jellydn/lazy-nvim-ide) with Docker. You might see this usage on other NVim distributions.
```sh
docker run -w /root -it --rm alpine:latest sh -uelic '
  apk add git nodejs neovim ripgrep build-base --update
  git clone https://github.com/LazyVim/starter ~/.config/nvim
  nvim
  '
```

**Comment by folke** [comment]
Check the docs. You can find the docker instructions there.
