### ISSUE TITLE
Add requirement for "node" to starter installation instructions

### ISSUE THREAD

**Issue by randomouscrap98** [LazyVim/starter#32]
Not everyone has node installed. I followed the instructions as given in https://www.lazyvim.org/ and installed all requirements, but upon initial start of nvim (and all subsequent starts) Mason threw an error for being "unable to install jsonls". Installing node fixed this, though I'm not sure if that's what should be the default.

In any case, I think that if the starter requires node to not throw an error every time, it should at least be mentioned in the requirements if that's OK. Or remove jsonls from the defaults.

**Comment by folke** [comment]
Fixed in https://github.com/LazyVim/LazyVim/commit/fa6cbfc6020efcd2168ffe09a209037599b91442
