### ISSUE TITLE
set lazy.nvim options

### ISSUE THREAD

**Issue by max397574** [LazyVim/starter#35]
I hope it's right to open issues in this place instead of lazyvim/lazyvim
So I couldn't find an example in the docs on how to set lazy.nvim options, specifically the `dev` option. I tried looking at your personal config in folke/dot repo but it looks like this differs quite a lot from the current starter template.

**Comment by folke** [comment]
You can set those here https://github.com/LazyVim/starter/blob/92b2689e6f11004e65376e84912e61b9e6c58827/lua/config/lazy.lua#L9
