### ISSUE TITLE
nvim crashes instantly after installing lazy starter

### ISSUE THREAD

**Issue by FlorianWieser1** [LazyVim/starter#37]
Dear authors, 

I'd love to try out lazy, as it  has so many features out of the box. On my local machine installation worked without any issues. However, on our scientific cluster it instantly crashes when opening nvim again after lazy installation. I tried all versions of nvim supported by lazy,  but always the same crash. 
Before installation, i removed everything from .config/nvim and .local/share/bin/nvim. I'm far from beeing a vim or nvim expert, I can't even provide you an error log as I don't know where to look for it (?).
Any help is appreciated! Thank you in advance!

**Comment by folke** [comment]
If your Neovim install crashes, then that's not LazyVim.
Check the Neovim wiki on how to get a stacktrace.

Also make sure you use a stable version or a recent nightly
