### ISSUE TITLE
Couldn't resolve host: github.com when updating plugins

### ISSUE THREAD

**Issue by Hamza12700** [LazyVim/starter#39]
Whenever I try to update plugins every single time it gives me this error message `Could not resolve host: github.com`
![image](https://github.com/LazyVim/starter/assets/72913359/c6809cd6-86fe-420d-9344-6b9566675ad5)

I even tried deleting `~/.local/share/nvim`, `~/.local/state/nvim` and `~/.cache/nvim` but still the same issue.

**Neovim Version:** `NVIM v0.10.0-dev`

**Comment by briandipalma** [comment]
Is this working for you now? Can you clone from the command line, the same one you use when you open neovim?
