### ISSUE TITLE
lazyvim.config.options no such option: 'splitkeep'

### ISSUE THREAD

**Issue by altosys** [LazyVim/starter#4]
After cloning the starter repo into my `~/.config/nvim`  and starting neovim up for the second time after lazy bootstraps all the plugins I keep getting this error on startup:

```
Error detected while processing /home/user/.config/nvim/init.lua:
Failed loading lazyvim.config.options
vim/_meta.lua:0: no such option: 'splitkeep'
# stacktrace:
  - vim/_meta.lua:0 _in_ **__index**
  - vim/_meta.lua:0 _in_ ****
  - vim/_meta.lua:0 _in_ **__newindex**
  - /LazyVim/lua/lazyvim/config/options.lua:52
  - /LazyVim/lua/lazyvim/config/init.lua:118
  - /LazyVim/lua/lazyvim/config/init.lua:117 _in_ **load**
  - /LazyVim/lua/lazyvim/plugins/init.lua:4
  - lazy.lua:9
```

My nvim (`neovim-nightly-bin` from AUR):
```
NVIM v0.9.0-dev-16-g56998feeb
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

**Comment by folke** [comment]
You're using a very old nightly. Either use the latest stable or the latest nightly.

See here https://github.com/LazyVim/LazyVim/blob/3dd367caac063323fb53f8f768c5bcd5f04eb8c8/lua/lazyvim/config/options.lua#L51
