### ISSUE TITLE
Toggle UI

### ISSUE THREAD

**Issue by luzik** [LazyVim/starter#40]
I have trouble making my clipboard working over ssh (complicated and not related to this issue). I found that selecting text with shift is a very easy and working all the way solution, the only problem is that to copy file text only, I have to hide
1. Line numbers
2. Indentation signs |
3. Linting errors
4. more..

Would be awesome to have a possibility to toggle all UI options off and on. Ideally with Shift down

**Comment by folke** [comment]
please use discussions in the LazyVim repo instead
