### ISSUE TITLE
Unable to delete/clean plugins with use of lazy

### ISSUE THREAD

**Issue by romanshevchenkokwiff** [LazyVim/starter#42]
Was trying to remove plugins that not planing to use, though have stumbled on such issue

nvim version 0.9.4
Windows wsl2 Ubuntu latest(22.04)

![image](https://github.com/LazyVim/starter/assets/96050177/4e78e908-7962-4cdc-8d7b-f367c230462a)

**Comment by briandipalma** [comment]
What did you do to remove them? Did you go into the filesystem and delete them?

**Comment by folke** [comment]
You probably already deleted them on the filesystem while Neovim was open?
I just fixed that error message, but it would only show if the plugin's directory no longer exists.
