### ISSUE TITLE
Not found lazy.nvim

### ISSUE THREAD

**Issue by shifengren** [LazyVim/starter#44]
I clone `lazy.nvim` in `~/.local/share/nvim` (vim.fn.stdpath("data") print this path), join `/lazy/lazy.nvim`, rtp.prepend `lazypath`, and then `require(lazy.nvim)`, nvim produce the following errors. how to fix ?

<img width="538" alt="image" src="https://github.com/LazyVim/starter/assets/13633999/e75ddcae-08b4-43d0-9ca8-35c1d130c5c9">

<img width="688" alt="image" src="https://github.com/LazyVim/starter/assets/13633999/e850b5be-f5f0-4a4c-aa3c-0ef22f6367e5">

**Comment by briandipalma** [comment]
lazy.nvim and LazyVim are two different packages. Don't confuse them two.

**Comment by folke** [comment]
Your initial git checkout must have failed. Bad internet?
