### ISSUE TITLE
Explain how to configure the plugins

### ISSUE THREAD

**Issue by zfogg** [LazyVim/starter#48]
How do i configure the plugins that this automatically installs? I need to configure flash.nvim for instance because I use `,` as my leader key

**Comment by zfogg** [comment]
how is the lazy-lock full of files already after install? the list of plugins in lazy.lua doesn't include flash.nvim but it gets installed...

**Comment by zfogg** [comment]
just curious how to remove stuff if i want to

**Comment by briandipalma** [comment]
LazyVim uses lazy.nvim as its plugin manager so I'd start by reading up on it here https://github.com/folke/lazy.nvim and in the documentation you should now have in neovim. This https://github.com/briandipalma/iac/blob/main/dotfiles/nvim/lua/plugins/disabled.lua is an example of how to disable plugins. After you disable a plugin lazy.nvim will give you the option to clean/remove it.

**Comment by zfogg** [comment]
i got it all figured out, thank you for the support. closing the issue but hopefully other people on google will find this :)
