### ISSUE TITLE
where to put mapleader

### ISSUE THREAD

**Issue by zfogg** [LazyVim/starter#50]
```lua
-- init.vim
vim.g.mapleader = ','
require("config.lazy")
```

this doesn't actually work.. my mapleader is still `<space>` after everything loads. i can get it working by putting my mapleader in a plugin/keys.vim file but then i get this message:

```
You need to set `vim.g.mapleader` **BEFORE** loading lazy
```

i'm not sure where to put it to make it work without getting that error message every startup

**Comment by zfogg** [comment]
i will just disable flash.nvim until you can tell me how to override it :)

**Comment by briandipalma** [comment]
Have you tried the options.lua file? https://github.com/briandipalma/iac/blob/main/dotfiles/nvim/lua/config/options.lua if you cloned this repo you should have one in the same location.

**Comment by zfogg** [comment]
thanks!
