### ISSUE TITLE
Neovim 'uv' Field Access Error: Attempt to index field 'uv' (a nil value)

### ISSUE THREAD

**Issue by wesleepnl** [LazyVim/starter#55]
<img width="896" alt="image" src="https://github.com/LazyVim/starter/assets/163451590/9f8ae05b-3bdf-4f09-9ca5-2dca61908b62">

### my step

```zsh
mv ~/.config/nvim{,.bak}
mv ~/.local/share/nvim{,.bak}
mv ~/.local/state/nvim{,.bak}
mv ~/.cache/nvim{,.bak}

git clone https://github.com/LazyVim/starter ~/.config/nvim

nvim
```

### version

NVIM: v0.9.5
OS: macOS Sonoma 14.4

**Comment by folke** [comment]
should be fixed already
