### ISSUE TITLE
nvim .9 breaking on yank.

### ISSUE THREAD

**Issue by aaronjconway** [LazyVim/starter#6]
nvim v0.9.0-dev
pop os

steps to reproduce

git clone https://github.com/LazyVim/starter ~/.config/nvim
wait for install. 
f into a file
yy -> death. 

 
![Screenshot from 2023-01-13 02-02-54](https://user-images.githubusercontent.com/14149952/212281356-e4e6843b-8c2a-45b0-9e12-b3ffb72debdf.png)

![Screenshot from 2023-01-13 02-06-05](https://user-images.githubusercontent.com/14149952/212281426-d1f937d0-5685-4f1e-a3bf-4fb0943b809d.png)

**Comment by folke** [comment]
Yeah, that's a known issue. For more information, check:
https://github.com/folke/noice.nvim/issues/298

The issue is caused by https://github.com/neovim/neovim/issues/21604
