### ISSUE TITLE
Tab in insert mode <anonymous>

### ISSUE THREAD

**Issue by phuongpd2k** [LazyVim/starter#68]
Which lib was this tab shortcut installed from? How can I remove it? Can someone help me? This creates a conflict when I install copilot :(
<img width="1203" alt="image" src="https://github.com/LazyVim/starter/assets/65531653/6d667b7d-1cf1-4222-8175-5dada79aa87e">

**Comment by folke** [comment]
tab is used to navigate in snippets

**Comment by phuongpd2k** [comment]
Is there any way I can unmap Tab : <anonymous>? :((

**Comment by briandipalma** [comment]
LazyVim has a copilot extra I believe, are you using it?
