### ISSUE TITLE
How can I use starter with dot file manager like Chezmoi?

### ISSUE THREAD

**Issue by dfdgsdfg** [LazyVim/starter#7]
I cloned every Nvim config introduced from the document.
```bash
git clone https://github.com/LazyVim/starter ~/.config/nvim
```

And I feel... WOW! 👍 👍 👍 💯 

At this moment everything is just perfect, but I need some custom things and should manage it.

Any suggestions?

**Comment by folke** [comment]
I have no idea how Chezmoi works. That's something you need to figure out yourself.

But fyi. you can remove the `~.config/nvim/.git` folder. The starter only contains some templates, you can put the files anywhere you want. (git or chezmoi, or whatever)

**Comment by dfdgsdfg** [comment]
@folke everything is just beautiful! I drop all my own configs. Thanks for your really great work.

By the way, probably some users want to guide how to work with a dot file manager.

So maybe your comment should be in the doc as FAQ.

Cheers!

**Comment by folke** [comment]
Good point. I will add a not that the `.git` folder should be removed.

**Comment by luxus** [comment]
maybe curl it directly, chezmoi supports downloading zips as well 
curl -L https://github.com/<user>/<repo-name>/archive/refs/tags/v1.2.3.zip | tar xz
