### ISSUE TITLE
TAB key does not work as before

### ISSUE THREAD

**Issue by sweet2honey** [LazyVim/starter#78]
I'm new to lazyvim and have been using a version installed months ago.
Recently i have tried updated lazyvim, and I found the `TAB` key does not work well.

It gives some error like:
```
E5108: Error executing lua: ...ng/nvim-data/lazy/LazyVim/lua/lazyvim/plugins/coding.lua:100: attempt to index field 'snippet' (a nil value)
stack traceback:
	...ng/nvim-data/lazy/LazyVim/lua/lazyvim/plugins/coding.lua:100: in function <...ng/nvim-data/lazy/LazyVim/lua/lazyvim/plugins/coding.lua:99>
```

I've tried reinstalled and it does not help.

**Comment by folke** [comment]
that's because you're on an old nightly.
Either use a stable release or a recent nightly.
And next time, please use Github discussions in the LazyVim repo.
