### ISSUE TITLE
Tokyonight and habamax gets installed by default.

### ISSUE THREAD

**Issue by vdegenne** [LazyVim/starter#89]
https://github.com/LazyVim/starter/blob/cb6349c8ae922d1c5745574f4d17b44f2731d451/lua/config/lazy.lua#L33

If I remove all nvim caches from my system and remove these two themes from the starter and restart nvim, I ended having them installed anyways. Are they left in the starter for historical reason?

**Comment by folke** [comment]
Habamax is a Neovim builtin colorscheme.
Tokyonight is the default theme for LAzyVim.

**Comment by vdegenne** [comment]
Ok thanks for the info. I think I understand why `tokyonight` is there, if I install a new theme e.g. gruvbox and set it as the default, I could still use tokyonight from `<leader>uC` menu. But `habamax` could be removed from the list since it is now shipped with neovim directly.
